# Generated by Django 5.0.7 on 2024-07-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_App', '0002_order_delete_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Product_Name',
            new_name='Name',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
