# Generated by Django 5.0.7 on 2024-07-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_App', '0003_rename_product_name_products_name_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Created_by',
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_id',
            field=models.IntegerField(),
        ),
    ]
