# Generated by Django 5.0.7 on 2024-07-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_App', '0004_remove_products_created_by_alter_products_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Status',
        ),
    ]
