# Generated by Django 5.0.7 on 2024-07-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_App', '0005_remove_products_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Product_id',
        ),
        migrations.AddField(
            model_name='category',
            name='Descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='Stock',
            field=models.FloatField(),
        ),
    ]
